version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.10

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=ECR_IMAGE_TAGE}

  build:
    commands:
      - echo "Building docker image..."
      - docker build -t $ECR_IMAGE_REPO_URL:latest .
      - docker tag $ECR_IMAGE_REPO_URL:latest $ECR_IMAGE_REPO_URL:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing the docker images..."
      - docker push $ECR_IMAGE_REPO_URL:latest
      - docker push $ECR_IMAGE_REPO_URL:$IMAGE_TAG
      - echo ""
      - echo "Creating the taskdef.json file..."
      - cd scripts && python3 generate_taskdef_and_appspec.py

artifacts:
  files:
    - appspec.yml
    - taskdef.json
